### ISSUE TITLE
CI dependencies for .gitlab-ci.yml

### ISSUE THREAD

**Issue by humb1t** [PistonDevelopers/glfw-rs#345]
Hello, I use glfw-rs in my study project, but I can't build it with gitlab CI because of:

> error: linking with `cc` failed: exit code: 1
> note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/builds/humb1t/anduin/target/release/anduin.0.o" "-o" "/builds/humb1t/anduin/target/release/anduin" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/builds/humb1t/anduin/target/release" "-L" "/builds/humb1t/anduin/target/release/deps" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/builds/humb1t/anduin/target/release/deps/libglfw-5463f6def31be3c0.rlib" "/builds/humb1t/anduin/target/release/deps/libenum_primitive-2dc0d7f5a40461af.rlib" "/builds/humb1t/anduin/target/release/deps/liblog-30a8a27ec161f1be.rlib" "/builds/humb1t/anduin/target/release/deps/libsemver-37abe19657aa486f.rlib" "/builds/humb1t/anduin/target/release/deps/libnom-bece7a6cd9d097d9.rlib" "/builds/humb1t/anduin/target/release/deps/libtime-6a04ec8d5f6fa0d3.rlib" "/builds/humb1t/anduin/target/release/deps/libnum-789f434bcaf1d3d0.rlib" "/builds/humb1t/anduin/target/release/deps/libnum_complex-ee6a431acf3b7953.rlib" "/builds/humb1t/anduin/target/release/deps/libnum_rational-0e5c64fb3493f285.rlib" "/builds/humb1t/anduin/target/release/deps/libnum_bigint-ead528cb8085b46e.rlib" "/builds/humb1t/anduin/target/release/deps/libbitflags-01727bf67df6b16b.rlib" "/builds/humb1t/anduin/target/release/deps/libnum_iter-87c7b38a4ca2f48d.rlib" "/builds/humb1t/anduin/target/release/deps/libnum_integer-f9f88e0f093fcdba.rlib" "/builds/humb1t/anduin/target/release/deps/libnum_traits-a4000e09af4c8117.rlib" "/builds/humb1t/anduin/target/release/deps/librand-6fab17fc670a2bc8.rlib" "/builds/humb1t/anduin/target/release/deps/liblibc-12d5d911cf5411c3.rlib" "/builds/humb1t/anduin/target/release/deps/librustc_serialize-d9e72695d437325f.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-4fda350b.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-4fda350b.rlib" "-l" "glfw" "-l" "X11" "-l" "GL" "-l" "Xxf86vm" "-l" "Xrandr" "-l" "Xi" "-l" "Xcursor" "-l" "Xinerama" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "compiler-rt"
> note: /usr/bin/ld: cannot find -lglfw
> /usr/bin/ld: cannot find -lX11
> /usr/bin/ld: cannot find -lGL
> /usr/bin/ld: cannot find -lXxf86vm
> /usr/bin/ld: cannot find -lXrandr
> /usr/bin/ld: cannot find -lXi
> /usr/bin/ld: cannot find -lXcursor
> /usr/bin/ld: cannot find -lXinerama
> collect2: error: ld returned 1 exit status

Link to CI [error](https://gitlab.com/humb1t/anduin/builds/1334991).
You can refuse this issue of course.

**Comment by humb1t** [comment]
```
image: iceyec/ci-rust

build:
  before_script:
    # some native deps
    - sudo apt-get -y install software-properties-common python-software-properties
    - sudo add-apt-repository ppa:git-core/ppa
    - sudo apt-get update
    - sudo apt-get -y install cmake libXxf86vm-dev libxinerama-dev libxcursor-dev git xorg-dev
    # glfw
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - sudo apt-get -y build-dep glfw
    - cmake -DBUILD_SHARED_LIBS=ON
    - make
    - sudo make install
    - cd ..
    - export LD_LIBRARY_PATH=/usr/local/lib
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - cargo build --release --verbose
```
That works for me.
